# Generated by Django 3.2.16 on 2024-01-25 10:22

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20240123_1132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('pub_date',)},
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(condition=models.Q(('user', django.db.models.expressions.F('following'))), fields=('user',), name='unique_user_self_following'),
        ),
    ]
